version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.4
    - 24.3.5
  - dependency-name: provviz
    versions:
    - 1.19.5
    - 1.20.2
    - 1.36.0
    - 1.37.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: monaco-editor-webpack-plugin
    versions:
    - 3.0.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: jest-resolve
    versions:
    - 26.6.2
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: "@svgr/webpack"
    versions:
    - 5.5.0
  - dependency-name: web-vitals
    versions:
    - 1.1.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: postcss-flexbugs-fixes
    versions:
    - 5.0.1
  - dependency-name: postcss-normalize
    versions:
    - 9.0.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
